language: node_js
node_js:
  - "7" #latest
  - "6" #LTS
services:
  - postgresql
before_script:
  - psql -U postgres -c "CREATE ROLE expresspg_test_admin PASSWORD 'md5b5fba89dc8b40773ed48b0505af53f95' NOSUPERUSER CREATEDB CREATEROLE INHERIT LOGIN"
  - psql -U postgres -c "CREATE DATABASE expresspg_test WITH OWNER expresspg_test_admin;"
